---
title: "Final"
author: "Xie Jiaxin, 2020111142"
date: "`r Sys.Date()`"
output: html_document
---

# 载入相关包

```{r}
library(tidyverse)
library(patchwork)
library(purrr)
```

# 导入数据

```{r}
rm(list = ls())
data <- read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
```

# 数据预处理

```{r}
data <- data[,-1] #删除ID列
data$Churn <- factor(data$Churn,labels = c("0","1")) #响应变量因子化
sum(is.na(data))
data <- na.omit(data)
summary(data)

# 类别合并
data$MultipleLines[data$MultipleLines == 'No phone service'] <- 'No'
data$OnlineSecurity[data$OnlineSecurity == 'No internet service'] <- 'No'
data$OnlineBackup[data$OnlineBackup == 'No internet service'] <- 'No'
data$DeviceProtection[data$DeviceProtection == 'No internet service'] <- 'No'
data$TechSupport[data$TechSupport == 'No internet service'] <- 'No'
data$StreamingTV[data$StreamingTV == 'No internet service'] <- 'No'
data$StreamingMovies[data$StreamingMovies == 'No internet service'] <- 'No'

# 数据类型处理
data <- data %>%
  mutate(SeniorCitizen = as.character(SeniorCitizen)) %>%
  mutate_if(is.character,factor,ordered=F)

sapply(data,class)
```

# 探索性数据分析

```{r}
### 卡方检验 分类变量
# gender  不显著
pv1 <- chisq.test(table(data$gender,data$Churn))$p.value
p1 <- ggplot(data = data) + 
  geom_bar(mapping = aes(x = gender, fill = Churn), position = "fill")

# SeniorCitizen
pv2 <- chisq.test(table(data$SeniorCitizen,data$Churn))$p.value
p2 <- ggplot(data=data) +
  geom_bar(mapping = aes(x = SeniorCitizen, fill = Churn), position = "fill")

# Partner       
pv3 <- chisq.test(table(data$Partner,data$Churn))$p.value
p3 <- ggplot(data=data) +
  geom_bar(mapping = aes(x = Partner, fill = Churn), position = "fill")

# Dependents
pv4 <- chisq.test(table(data$Dependents,data$Churn))$p.value
p4 <- ggplot(data=data) +
  geom_bar(mapping = aes(x = Dependents, fill = Churn), position = "fill")

# PhoneService  不显著
pv5<-chisq.test(table(data$PhoneService,data$Churn))$p.value
p5 <- ggplot(data=data) +
  geom_bar(mapping = aes(x = PhoneService, fill = Churn), position = "fill")

# MultipleLines  无意义
pv6<-chisq.test(table(data$MultipleLines,data$Churn))$p.value
p6 <- ggplot(data=data) +
  geom_bar(mapping = aes(x = MultipleLines, fill = Churn), position = "fill")

# InternetService
pv7<-chisq.test(table(data$InternetService,data$Churn))$p.value
p7 <- ggplot(data=data) +
  geom_bar(mapping = aes(x = InternetService, fill = Churn), position = "fill")

# OnlineSecurity
pv8<-chisq.test(table(data$OnlineSecurity,data$Churn))$p.value
p8 <- ggplot(data=data) +
  geom_bar(mapping = aes(x = OnlineSecurity, fill = Churn), position = "fill")

# OnlineBackup
pv9<-chisq.test(table(data$OnlineBackup,data$Churn))$p.value
p9 <- ggplot(data=data) +
  geom_bar(mapping = aes(x = OnlineBackup, fill = Churn), position = "fill")

# DeviceProtection
pv10<-chisq.test(table(data$DeviceProtection,data$Churn))$p.value
p10 <- ggplot(data=data) +
  geom_bar(mapping = aes(x = DeviceProtection, fill = Churn), position = "fill")

# TechSupport
pv11<-chisq.test(table(data$TechSupport,data$Churn))$p.value
p11 <- ggplot(data=data) +
  geom_bar(mapping = aes(x = TechSupport, fill = Churn), position = "fill")

# StreamingTV
pv12<-chisq.test(table(data$StreamingTV,data$Churn))$p.value
p12 <- ggplot(data=data) +
  geom_bar(mapping = aes(x = StreamingTV, fill = Churn), position = "fill")

# StreamingMovies
pv13<-chisq.test(table(data$StreamingMovies,data$Churn))$p.value
p13 <- ggplot(data=data) +
  geom_bar(mapping = aes(x = StreamingMovies, fill = Churn), position = "fill")

# Contract
pv14<-chisq.test(table(data$Contract,data$Churn))$p.value
p14 <- ggplot(data=data) +
  geom_bar(mapping = aes(x = Contract, fill = Churn), position = "fill")

# PaperlessBilling
pv15<-chisq.test(table(data$PaperlessBilling,data$Churn))$p.value
p15 <- ggplot(data=data) +
  geom_bar(mapping = aes(x = PaperlessBilling, fill = Churn), position = "fill")

# PaymentMethod
pv16<-chisq.test(table(data$PaymentMethod,data$Churn))$p.value
p16 <- ggplot(data=data) +
  geom_bar(mapping = aes(x = PaymentMethod, fill = Churn), position = "fill")

p1+p2+p3+p4+p5+p6+p7+p8+p9+p10+p11+p12+p13+p14+p15+p16

### 单因素方差分析
# tenure
tenure.aov <- aov(data$tenure~data$Churn)
pv17<-summary(tenure.aov)[[1]][["Pr(>F)"]][1]

# MonthlyCharges
MonthlyCharges.aov <- aov(data$MonthlyCharges~data$Churn)
pv18<-summary(MonthlyCharges.aov)[[1]][["Pr(>F)"]][1]

# TotalCharges
TotalCharges.aov <- aov(data$TotalCharges~data$Churn)
pv19<-summary(TotalCharges.aov)[[1]][["Pr(>F)"]][1]

p17 <- ggplot(data=data) +
  geom_boxplot(mapping = aes(x = Churn, y = tenure, fill=Churn))
p18 <- ggplot(data=data) +
  geom_boxplot(mapping = aes(x = Churn, y = MonthlyCharges, fill=Churn))
p19 <- ggplot(data=data) +
  geom_boxplot(mapping = aes(x = Churn, y = TotalCharges, fill=Churn))

p17+p18+p19

# p-value plot
pv<- c(pv1,pv2,pv3,pv4,pv17,pv5,pv6,pv7,pv8,pv9,pv10,pv11,pv12,pv13,pv14,pv15,pv16,pv18,pv19)
p.frame <- data.frame(feature = names(data[-20]),P.value = pv)
p.frame <- p.frame[order(p.frame$P.value),]
p.frame$feature <- factor(p.frame$feature,levels = p.frame$feature)
ggplot(data = p.frame,aes(x = feature, y = P.value)) + 
  geom_pointrange(aes(ymin=0,ymax=P.value),
                  size = 0.5,
                  color = ifelse(p.frame$P.value>0.001,'#F8766D','grey'))+
  coord_flip()
```

# 剔除不显著

```{r}
data <- data %>%
  dplyr::select(-gender,-PhoneService,-MultipleLines)
```

# Logistic模型
## 导入相关包
```{r}
library(tidyverse)
library(patchwork)
library(GGally)
library(pROC)
library(highcharter)
library(caret)
data.all <- data
```

## 数据分箱
### 一维高斯混合模型
```{r}
#高斯混合模型的一维情形，用来对连续变量分箱
#输入：数据向量，聚类簇 数
#输出：聚类结果和高斯分布的参数
#方法： EM算法
GMMML <- function(x,k=4,eps=1e-8){
  x <- scale(x)%>%as.vector
  #初值
  mu <- quantile(x,seq(0,1,length=k+3))[2:(k+1)]
  pai <- rep(1/k,length=k)
  sigma <-rep(2,k)
  #计算 rik
  calculate_r <- function(x,mu,sigma,pai,k){
    #返回列表，个数为 k，每个长度为样本数
    a1 <- map(1:k,~exp(-(x-mu[.])^2/(2*sigma[.]))*pai[.]/sqrt(sigma[.]))
    p <- rep(0,length(a1[[1]]))
    for(m in 1:k){p <- p+a1[[m]]}
    for(m in 1:k){a1[[m]] <- a1[[m]]/p}
    return(a1)
  }
  #准备迭代
  flag <- 1
  while(flag>eps){
    #r为列表，含有 k个元素，为 rik
    r <- calculate_r(x,mu,sigma,pai,k)
    R <- r%>%map_dbl(sum)
    mu.new <-(1:k)%>%
      map_dbl(~sum(r[[.]]*x)/R[.])
    sigma.new <- (1:k)%>%
      map_dbl(~sum(r[[.]]*(x-mu.new[.])^2)/R[.])
    pai.new <- R/length(r[[1]])
    #退出循环条件退出循环条件
    flag <- (mu.new-mu)%>%'^'(2)%>%sum+
      (sigma.new-sigma)%>%'^'(2)%>%sum+
      (pai.new-pai)%>%'^'(2)%>%sum
    #更新参数更新参数
    mu <- mu.new
    sigma <- sigma.new
    pai <- pai.new
  }
  #确定聚类结果确定聚类结果
  cluster_result <- r%>%as.data.frame%>%
    apply(1,which.max)
  result <- list(cluster=cluster_result,
                 parm=list(pai=pai,mu=mu,sigma=sigma))
  return(result)
}
```

### 对连续变量分箱
```{r}
dataCON <- data.all %>%
  dplyr::select(where(is.numeric),Churn)%>%
  as.data.frame
class(dataCON)
# tenure
tenure.clust<-GMMML(dataCON[,1],k=4,eps=1e-6)[[1]]
table(tenure.clust)#查看频数
p20 <- ggplot(cbind(data.all,类别=factor(tenure.clust)),aes(y=tenure,fill=类别 ))+
  geom_bar(position = 'fill')
data.all$tenure <- factor(tenure.clust)
table(data.all$tenure,data.all$Churn)%>%chisq.test()

# MonthlyCharges
MonthlyCharges.clust<-GMMML(dataCON[,2],k=4,eps=1e-6)[[1]]
table(MonthlyCharges.clust)#查看频数
p21 <- ggplot(cbind(data.all,类别=factor(MonthlyCharges.clust)),aes(y=MonthlyCharges,fill=类别 ))+
  geom_bar(position = 'fill')
data.all$MonthlyCharges <- factor(MonthlyCharges.clust)
table(data.all$MonthlyCharges,data.all$Churn)%>%chisq.test()

#
TotalCharges.clust<-GMMML(dataCON[,3],k=4,eps=1e-6)[[1]]
table(TotalCharges.clust)#查看频数
p22 <- ggplot(cbind(data.all,类别=factor(TotalCharges.clust)),aes(y=TotalCharges,fill=类别 ))+
  geom_bar(position = 'fill')
data.all$TotalCharges <- factor(TotalCharges.clust)
table(data.all$TotalCharges,data.all$Churn)%>%chisq.test()

p20+p21
```

## 评分卡模型
### WOE编码
```{r}
#给数据框 WOE编码
#输入：
#data：数据框
#y:因变量列名
#test：测试集数据框
#输出： WOE编码后的数据框和 IV值
#若有 test则再返回 test的编码结果
#注： test和 data的列名需要完全相同
WOEML <- function(data,y,test=NULL){
  flag <- 1
  if(is.null(test)){
    flag<- 0
    test <- data
  }
  result <- data%>%dplyr::select(eval(y))%>%unlist
  data <- data%>%dplyr::select(-eval(y))
  retest <- test%>%dplyr::select(eval(y))%>%unlist
  test <- test%>%dplyr::select(-eval(y))
  name <- names(data)
  IV <- rep(0,length(name))
  names(IV) <- name
  N0 <- table(result)["0"]
  N1 <- table(result)["1"]
  for(ii in 1:length(name)){
    M0 <- tapply(unlist(result),list(data[,ii],unlist(result)),length)%>%as.matrix
    for(jj in 1:nrow(M0)){
      WOE <- log((M0[jj,"1"]/M0[jj,"0"])/(N1/N0))
      IV[ii] <- IV[ii]+(M0[jj,"1"]/N1-M0[jj,"0"]/N0)*WOE
      levels(data[,ii])[which(levels(data[,ii])==rownames(M0)[jj])] <- WOE
      levels(test[,ii])[which(levels(test[,ii])==rownames(M0)[jj])] <- WOE
    }
    data[,ii] <- as.numeric(as.character(data[,ii]))
    test[,ii] <- as.numeric(as.character(test[,ii]))
  }
  data <- cbind(data,y=result)
  test <- cbind(test,y=retest)
  IV <- sort(IV)
  if(flag){
    return(list(data,IV,test))
  }else{
    return(list(data,IV))
  }
}
```

### 给所有变量编码
```{r}
data.all <- as.data.frame(data.all)
WOE <- WOEML(data.all,y="Churn")
data.WOE <- WOE[[1]]
# 相关性（all）
ggcorr(data.WOE[-17],label = T,digits = 2,hjust=0.8)
# 相关性（>0.5）
data.WOE %>%
  dplyr::select(tenure,InternetService,Contract,MonthlyCharges,TotalCharges)%>%
  ggcorr(label = T,digits = 2,hjust=0.8)
```

## 建模
### 特征筛选
```{r}
data.WOE.pro <- data.WOE %>%
  select(-MonthlyCharges) # 高度相关 保留其一
fit.logit <- glm(y~.,data.WOE.pro,family = binomial(link = "logit"))
summary(fit.logit)
# 删除系数小于0的
data.WOE.pro <- data.WOE.pro %>%
  select(-Partner,-DeviceProtection) 
fit.logit <- glm(y~.,data.WOE.pro,family = binomial(link = "logit"))
summary(fit.logit)
```

### 特征重要性
```{r}
data.all.select <- data.all[,-c(2,8,15)]
WOE <- WOEML(data.all.select,y="Churn")
WOE[[2]]
IV.frame <- data.frame(feature = names(WOE[[2]]),value = WOE[[2]])
IV.frame <- IV.frame[order(IV.frame$value),]
IV.frame$feature <- factor(IV.frame$feature,levels = IV.frame$feature)
ggplot(data = IV.frame,aes(x = value, y = feature)) + 
  geom_bar(stat = 'identity', 
           fill = ifelse(IV.frame$value>0.3,ifelse(IV.frame$value>=0.5,'#F8766D','#00BFC4'),'grey'), 
           width = 0.9)
```

### 模型评估
```{r}
### 划分数据集
set.seed(2020111142)
ind <- sample(1:nrow(data),size = 0.7*nrow(data))
train <- data[ind,-c(2,8,15)]
test <- data[-ind,-c(2,8,15)]

### 训练集分箱
trainCON <- train %>%
  dplyr::select(where(is.numeric),Churn)%>%
  as.data.frame
avg <- map_dbl(trainCON[1:2],mean)
std <- map_dbl(trainCON[1:2],sd)
cl1<-GMMML(trainCON[,1],k=4,eps=1e-6)
train$tenure <- factor(cl1[[1]])
cl2<-GMMML(trainCON[,2],k=4,eps=1e-6)
train$TotalCharges <- factor(cl2[[1]])

### 测试集分箱
testCON <- test %>%
  dplyr::select(where(is.numeric),Churn)%>%
  as.data.frame
#分箱 1
p <- rep(0,nrow(testCON))
t <- testCON[,1]
cl1 <- cl1[[2]]
for(j in 1:length(t)){
  q <- rep(0,4)
  for(k in 1:4){
    q[k] <- cl1$pai[k]*dnorm((t[j]-avg[1])/std[1],cl1$mu[k],sqrt(cl1$sigma[k]))
  }
  p[j] <- which.max(q)
}
test$tenure <- factor(p)
#分箱 2
p <- rep(0,nrow(testCON))
t <- testCON[,2]
cl2 <- cl2[[2]]
for(j in 1:length(t)){
  q <- rep(0,4)
  for(k in 1:4){
    q[k] <- cl1$pai[k]*dnorm((t[j]-avg[2])/std[2],cl1$mu[k],sqrt(cl1$sigma[k]))
  }
  p[j] <- which.max(q)
}
test$TotalCharges<- factor(p)

### WOE编码
train <- as.data.frame(train)
test <- as.data.frame(test)
WOE <- WOEML(train,y="Churn",test=test)
train.WOE <- WOE[[1]]
test.WOE <- WOE[[3]]

### 建模
train.WOE.fac <- train.WOE%>%
  mutate_if(is.numeric,factor,ordered=F)
test.WOE.fac <- test.WOE%>%
  mutate_if(is.numeric,factor,ordered=F)
fit.logit <- glm(y~.,train.WOE.fac,family = binomial(link = "logit"))
summary(fit.logit)

pred.logit.p <- predict(fit.logit,newdata = test.WOE.fac,type = 'response')

roc.logit <- roc(test.WOE.fac$y,pred.logit.p,quiet=T)
plot(roc.logit,print.auc=T,auc.polygon=T,grid=c(0.1,0.2),max.auc.polygon=T,auc.polygon.col='skyblue',print.thres=T)

pred.logit <- ifelse(pred.logit.p < 0.289,'0','1')
confusionMatrix(data = factor(pred.logit,levels = c('0','1')),reference = test.WOE.fac$y)

```

# Adaboost
## 导入相关包
```{r}
library(tidyverse)
```

## 决策树
```{r}
#决策树实现
#输入：
#x：自变量数据框
#y：因变量向量
#i：当前深度，调用取 0即可
#subset：该树可以试用的变量列
#weight：样本权重向量
#输出：列表嵌套结 构的决策树
#方法：递归
DTML <- function(x,y,i,subset,weight=rep(1,length(y))){
  w <- weight
  i <- i+1
  #停止准则
  if( (max(y)==min(y)) || i>max_iter || (length(subset)==0) ) {
    return(round(sum(y*w)/sum(w)))}
  #调用子函数找分裂点
  tvar <- FindPoint(x,y,subset,w)
  #判断信息增益率
  if(tvar[[2]]< 1e-6){
    return(round(sum(y*w)/sum(w)))}
  #分裂分裂
  data <- cbind(w,y,x)
  index <- which(eval(parse(text=paste0("data$",tvar[[1]]))))
  x1 <- data[index,]
  x2 <- data[-index,]
  y1 <- x1[,2]
  y2 <- x2[,2]
  w1 <- x1[,1]
  w2 <- x2[,1]
  x1 <- x1[,-c(1,2)]
  x2 <- x2[,-c(1,2)]
  #递归拿树递归拿树
  left.tree <- DTML(x1,y1,i,subset,w1)
  right.tree <- DTML(x2,y2,i,subset,w2)
  return(list(condition=tvar[[1]],
              Left =left.tree,
              Right=right.tree))
}
#查找最佳分裂点的子函数查找最佳分裂点的子函数
FindPoint <- function(x,y,subset,weight=8){
  w <- weight
  #计算交叉熵计算交叉熵H(t)
  n <- length(y)
  H <- cross.entropy(y,weight=w)
  #寻找分裂结点寻找分裂结点
  x <- x%>%select(subset)
  x1 <- x%>%select(where(is.numeric))#连连续型续型
  x2 <- x%>%select(where(is.factor))#因子因子型型
  #对变量循环对变量循环
  tvar <- list(con="",fai=0,varname="")
  p <- ncol(x1)
  if(p>0){
    for(ii in 1:p){
      a <- sort(unique(x1[,ii]))
      a <- (a[1:(length(a)-1)]+a[-1])/2
      a <- a[sample(length(a),min(30,length(a)))]
      #对取值循环对取值循环
      for(jj in a){
        p0 <- y[x1[,ii]<=jj]#左节左节点点
        Htl <- cross.entropy(p0,weight=w[x1[,ii]<=jj])
        p1 <- y[x1[,ii]>jj]
        Htr<- cross.entropy(p1,weight=w[x1[,ii]>jj])#右节右节点点
        #计算信息增益计算信息增益
        fai <- H-
          sum(w[x1[,ii]<=jj])/sum(w)*Htl-
          sum(w[x1[,ii]>jj])/sum(w)*Htr
        if(fai>tvar[[2]]){
          tvar[[2]] <- fai
          tvar[[3]] <- names(x1)[ii]
          tvar[[1]] <- paste0(names(x1)[ii],"<=",jj)
        }
      }
    }
  }
  p <- ncol(x2)
  if(p>0){
    for(ii in 1:p){
      a <- which(table(x2[,ii])>0)%>%names
      xf <- as.character(x2[,ii])
      #对取值循环对取值循环
      for(jj in 1:20){
        b <- 0
        while(sum(b)==0){b <- sample(2,length(a),T)-1}
        p0 <- y[xf %in% a[b]]#左左节点节点
        Htl <- cross.entropy(p0,weight=w[xf %in% a[b]])
        p1 <- y[!(xf %in% a[b])]
        Htr<- cross.entropy(p1,weight=w[!(xf %in% a[b])])#右节点右节点
        #计算信息增益计算信息增益
        fai <- H-
          sum(w[xf %in% a[b]])/sum(w)*Htl-
          sum(w[!(xf %in% a[b])])/sum(w)*Htr
        if(fai>tvar[[2]]){
          tvar[[2]] <- fai
          tvar[[3]] <- names(x2)[ii]
          d <- "c("
          for(m in unique(a[b])){d <- paste0(d,"\"",m,"\"",",")}
          d <- substr(d,1,nchar(d)-1)
          d <- paste0(d,")")
          tvar[[1]] <- paste0(names(x2)[ii]," %in% ",d)
        }
      }
    }
  }
  return(tvar)
}
#决策树的子函数：计算交叉熵决策树的子函数：计算交叉熵
cross.entropy <- function(y,weight=1){
  if(length(unique(y))<=1){return(0)}
  P1 <- sum(y*weight)/sum(weight)
  P0 <- 1-P1
  H <- -P0*log(P0)-P1*log(P1)
  return(H)
}
#决策树预测函数决策树预测函数
#输入：输入：
#modeltree：模型；：模型；x：自变量数据框：自变量数据框
#输出：分类结果向量输出：分类结果向量
#方法：递归方法：递归
pred.tree <- function(modeltree,x){
  if(nrow(x)<1){return(NULL)}
  re <- rep(-1,nrow(x))
  a <- modeltree
  #停止准则停止准则
  if(!is.list(a)){return(rep(a,nrow(x)))}
  #分裂分裂
  p <- which(eval(parse(text=paste0("x$",a[[1]]))))#左孩子行号左孩子行号
  if(length(p)<1){#全进右边全进右边
    x2 <- x
    b<- pred.tree(modeltree = a[[3]],x=x2)
    if(!is.null(b)){re <- b}
  }else{
    x1 <- x[p,] #进左进左
    x2 <- x[-p,]
    b <- pred.tree(modeltree = a[[2]],x=x1)
    if(!is.null(b)){re[p] <- b}
    b<- pred.tree(modeltree = a[[3]],x=x2)
    if(!is.null(b)){re[-p] <- b}
  }
  return(re)
}
```

## Adaboost
```{r}
#adaboost实现代码
#输入：
#x:自变量数据框
#y:因变量向量 {0,1}
#M：弱学习器个数
#输出：每个弱学习器和各自的权重
AdaboostML <- function(x,y,M=5,subset=names(x),max_iter=5){
  n <- nrow(x)
  w <- rep(1/n,n)
  L <- list()
  alpha <- c()
  for(iii in 1:M){
    #拟合弱分类器
    L1 <- DTML(x=x,y=y,i=0,subset=subset,weight = w)
    pred <- pred.tree(L1,x=x) *2-1
    err <- sum(w*(pred!=(y*2-1)))
    if(err==0 || err>=0.5 ){break}
    alpha1 <- 0.5*log((1-err)/err)
    if(is.na(alpha1) || alpha1<0){next}
    w <- w*exp(-(y*2-1)*alpha1*pred)
    w <- w/sum(w)
    L[[iii]] <- L1
    alpha[iii] <- alpha1
  }
  return(list(L,alpha))
}
#adaboost模型预测代码
#输入：
#L：模型 test：测试自变量
#输出：分类结果
pred.adaboost <- function(L,test){
  M <- length(L[[1]])
  re <- map(1:M,~( pred.tree( L[[1]][[.]], test )*2-1 ) *L[[2]][[.]])%>%
    as.data.frame%>%apply(1,sum)
  return(re)
}
```

## 模型建立
```{r}
### 划分数据集
set.seed(2020111142)
ind <- sample(1:nrow(data),size = 0.7*nrow(data))
train <- data[ind,]
test <- data[-ind,]

#训练预备
xt <- test%>%select(-Churn)%>%as.data.frame
yt <-test%>%select(Churn)%>%unlist%>%as.character%>%as.numeric
x <- train%>%select(-Churn)%>%as.data.frame
y <-train%>%select(Churn)%>%unlist%>%as.character%>%as.numeric
#训练模型
max_iter=2
L <- AdaboostML(x,y,M=50,subset=names(x),max_iter = 2)
#预测效果
pred.ada.fx <- pred.adaboost(L,xt)

roc.ada <- roc(as.factor(yt*2-1),pred.ada.fx,quiet=T)
plot(roc.ada,print.auc=T,auc.polygon=T,grid=c(0.1,0.2),max.auc.polygon=T,auc.polygon.col='skyblue',print.thres=T)

# 按最优阈值分类
pred.ada <- ifelse(pred.ada.fx<(-0.705),'0','1')
confusionMatrix(data = factor(pred.ada,levels = c('0','1')),reference = as.factor(yt))
```

# 随机森林
## 导入相关包
```{r}
library(randomForest)
```

## 建模
```{r}
# 划分数据集
set.seed(2020111142)
ind <- sample(1:nrow(data),size = 0.7*nrow(data))
train <- data[ind,]
test <- data[-ind,]

train <- as.data.frame(train)

# 验证集
ind.val <- sample(1:nrow(train),size = 0.7*nrow(train))
val.train <- train[ind.val,]
val <- train[-ind.val,]

# 调参
acc.test <- numeric()
accuracy1 <- NULL
accuracy2 <- NULL
for(i in 1:16){
  set.seed(2020111142)
  rf.train<-randomForest(Churn~.,data=val.train,mtry=i,ntree=1000)
  rf.pred <- predict(rf.train, val[,-17])
  accuracy1 <- confusionMatrix(rf.pred,val$Churn)
  accuracy2[i] <- accuracy1$overall[1]   
}
acc.test <- data.frame(p=1:16,cnt=accuracy2)
opt.p <- subset(acc.test,cnt==max(cnt))[1,]
sub <- paste("num of parameter:",opt.p$p,"    accuracy:", opt.p$cnt)
sub

hchart(acc.test,'line',hcaes(p,cnt))%>%
  hc_title(text='Accuracy With mtry(randomforest)')%>%
  hc_subtitle(text=sub)%>%
  hc_add_theme(hc_theme_google())%>%
  hc_xAxis(title=list(text = 'Number of Parameters'))%>%
  hc_yAxis(title=list(text = 'Accuracy'))

fit.rf <- randomForest(Churn~.,data = train,mtry=2,ntree=1000,proximity=T,importance=T)
plot(fit.rf,lwd=3,main = "Random Forest (Error Rate vs. Number of Trees)")
varImpPlot(fit.rf)

pre.rf.p <- predict(fit.rf,test[,-17],type="prob")[,1]
roc.rf <- roc(test$Churn,pre.rf.p,quiet=T)
plot(roc.rf,print.auc=T,auc.polygon=T,grid=c(0.1,0.2),max.auc.polygon=T,auc.polygon.col='skyblue',print.thres=T)

# 按最优阈值分类
pred.rf <- ifelse(pre.rf.p<0.704,'1','0')
confusionMatrix(data = factor(pred.rf,levels = c('0','1')),reference = test$Churn)

```

# 朴素贝叶斯
## 导入相关包
```{r}
library(e1071)
```

## 建模
```{r}
### 划分数据集
set.seed(2020111142)
ind <- sample(1:nrow(data),size = 0.7*nrow(data))
train <- data[ind,]
test <- data[-ind,]

fit.nb <- naiveBayes(train[,-17],train$Churn)
pred.nb.p <- predict(fit.nb,test[,-17],type='raw')[,1]
roc.nb <- roc(test$Churn,pred.nb.p,quiet=T)
plot(roc.nb,print.auc=T,auc.polygon=T,grid=c(0.1,0.2),max.auc.polygon=T,auc.polygon.col='skyblue',print.thres=T)

# 按最优阈值分类
pred.nb <- ifelse(pred.nb.p<0.511,'1','0')
confusionMatrix(data = factor(pred.nb,levels = c('0','1')),reference = test$Churn)
```



